name: ci-nodets

on:
  pull_request:
    branches:
      - develop

strategy:
  matrix:
    node-version: ['10.17.0', '17.9.0']

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
