name: ci-nodets

on:
  pull_request:
    branches:
      - develop


jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: ['16.14.0', '20.12.2']
=======
        node-version: ['10.17.0', '17.9.0']
>>>>>>> 9febeceed363d10fcca8d1c45a6ca5f3e729c702

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
